// SPDX-License-Identifier: BSL-1.0

//! The writers: a resolved `Generator` in, Zig and C source out.
//!
//! Everything here is a walk over the registry in its own order, so the output
//! does not depend on the order things were asked for in `wanted.zon` or on
//! anything that varies between runs.

const std = @import("std");
const Allocator = std.mem.Allocator;

const gen = @import("gen.zig");
const reg = @import("registry.zig");
const names = @import("names.zig");
const Generator = gen.Generator;
const Error = gen.Error;
const fail = gen.fail;

const Out = std.ArrayList(u8);

fn put(g: *Generator, out: *Out, comptime fmt: []const u8, args: anytype) Error!void {
    try out.print(g.arena, fmt, args);
}

/// One thing the C oracle measures and Zig has an opinion on, with both
/// spellings, so the two files cannot list them in different orders.
pub const Row = struct {
    label: []const u8,
    /// A Zig expression for a `u64`, in `layout.zig`, where `types` is the
    /// generated types.
    zig: []const u8,
    /// A C expression of type `unsigned long long`.
    c: []const u8,
};

const header_text =
    \\// SPDX-License-Identifier: BSL-1.0
    \\
    \\//! {s}
    \\//!
    \\//! GENERATED by `tools/genvk.zig` from the Vulkan registry. Do not edit: change
    \\//! `tools/wanted.zon` and run `zig build gen -Dvk-xml=<path to vk.xml>`.
    \\//!
    \\//! Registry: vk.xml, VK_HEADER_VERSION {s}.
    \\
;

fn header(g: *Generator, out: *Out, what: []const u8) Error!void {
    try put(g, out, header_text, .{ what, g.r.header_version });
}

fn banner(g: *Generator, out: *Out, title: []const u8) Error!void {
    try put(g, out, "\n// -------------------------------------------------------------------------\n// {s}\n// -------------------------------------------------------------------------\n\n", .{title});
}

/// A registry comment as a `///` line: one line, no leading `//`.
fn docLine(g: *Generator, out: *Out, indent: []const u8, text: []const u8) Error!void {
    var clean: std.ArrayList(u8) = .empty;
    var last_space = true;
    for (text) |c| {
        const is_space = c == ' ' or c == '\n' or c == '\r' or c == '\t';
        if (is_space) {
            if (!last_space) try clean.append(g.arena, ' ');
            last_space = true;
        } else {
            try clean.append(g.arena, c);
            last_space = false;
        }
    }
    var line = std.mem.trim(u8, clean.items, " ");
    if (std.mem.startsWith(u8, line, "//")) line = std.mem.trim(u8, line[2..], " ");
    if (line.len == 0) return;
    try put(g, out, "{s}/// {s}\n", .{ indent, line });
}

/// The `///` block above a declaration: the registry's name, and its comment.
fn doc(g: *Generator, out: *Out, indent: []const u8, reg_name: []const u8, comment: ?[]const u8) Error!void {
    try put(g, out, "{s}/// {s}\n", .{ indent, reg_name });
    if (comment) |c| {
        try put(g, out, "{s}///\n", .{indent});
        try docLine(g, out, indent, c);
    }
}

fn lessThanString(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

/// Every name a selected feature or extension asks for, as a set: the names of
/// types are how a promoted type's old alias is recognised as wanted.
fn requiredTypeNames(g: *Generator) Error!gen.Set {
    var set: gen.Set = .empty;
    for (g.r.providers) |p| {
        if (!g.isSelected(p.name)) continue;
        for (p.requires) |req| for (req.types) |t| try set.put(g.arena, t, {});
    }
    return set;
}

// -------------------------------------------------------------------------
// types.zig
// -------------------------------------------------------------------------

const Claimed = gen.Set;

fn claim(g: *Generator, claimed: *Claimed, zig_name: []const u8, reg_name: []const u8) Error!void {
    if (claimed.contains(zig_name))
        return fail(g.arena, "two registry names are both '{s}' in Zig (one is {s}): add a .rename to wanted.zon", .{ zig_name, reg_name });
    try claimed.put(g.arena, zig_name, {});
}

fn constantValue(g: *Generator, c: reg.Constant) Error![]const u8 {
    const text = std.mem.trim(u8, c.value, " ");
    const zig_type: []const u8 = if (std.mem.eql(u8, c.type_name, "uint64_t"))
        "u64"
    else if (std.mem.eql(u8, c.type_name, "uint32_t"))
        "u32"
    else if (std.mem.eql(u8, c.type_name, "float"))
        "f32"
    else
        return fail(g.arena, "API constant {s} has a type this generator does not know: {s}", .{ c.name, c.type_name });

    if (std.mem.eql(u8, zig_type, "f32")) {
        var digits = text;
        while (digits.len > 0 and (digits[digits.len - 1] == 'f' or digits[digits.len - 1] == 'F')) digits = digits[0 .. digits.len - 1];
        return std.fmt.allocPrint(g.arena, ": f32 = {s}", .{digits});
    }
    if (std.mem.startsWith(u8, text, "(~") and std.mem.endsWith(u8, text, ")")) {
        const number = reg.parseNumber(text[2 .. text.len - 1]) orelse
            return fail(g.arena, "API constant {s} has a value this generator cannot read: {s}", .{ c.name, text });
        return std.fmt.allocPrint(g.arena, ": {s} = ~@as({s}, {d})", .{ zig_type, zig_type, number });
    }
    const number = reg.parseNumber(text) orelse
        return fail(g.arena, "API constant {s} has a value this generator cannot read: {s}", .{ c.name, text });
    // A plain number stays a plain number: it is usually an array length, and
    // an untyped constant is what `[n]u8` wants.
    return std.fmt.allocPrint(g.arena, " = {d}", .{number});
}

pub fn types(g: *Generator, rows: *std.ArrayList(Row)) Error![]const u8 {
    var out: Out = .empty;
    var claimed: Claimed = .empty;
    try header(g, &out, "The Vulkan ABI: handles, enums, flags, structs, and the function pointers they hold.");

    try put(g, &out,
        \\
        \\const call = @import("../types.zig").call;
        \\
    , .{});
    if (g.w.methods.len > 0) try put(g, &out, "const methods = @import(\"../methods.zig\");\n", .{});
    try put(g, &out, "\n/// `VK_HEADER_VERSION` of the registry this was generated from.\npub const header_version = {s};\n", .{g.r.header_version});
    try claim(g, &claimed, "header_version", "VK_HEADER_VERSION");
    try claim(g, &claimed, "call", "VKAPI_CALL");
    try rows.append(g.arena, .{ .label = "VK_HEADER_VERSION", .zig = "types.header_version", .c = "(unsigned long long)(VK_HEADER_VERSION)" });

    // ---- constants ------------------------------------------------------
    {
        var list: std.ArrayList([]const u8) = .empty;
        var it = g.used_constants.keyIterator();
        while (it.next()) |k| try list.append(g.arena, k.*);
        std.mem.sort([]const u8, list.items, {}, lessThanString);

        if (list.items.len > 0) try banner(g, &out, "Constants");
        for (list.items) |name| {
            const c = g.r.constants.get(name).?;
            const zig_name = try g.constantZigName(name);
            try claim(g, &claimed, zig_name, name);
            try put(g, &out, "/// {s}\n", .{name});
            const value = try constantValue(g, c);
            try put(g, &out, "pub const {s}{s};\n", .{ zig_name, value });
            g.summary.constants += 1;
            if (!std.mem.eql(u8, c.type_name, "float")) {
                try rows.append(g.arena, .{
                    .label = name,
                    .zig = try std.fmt.allocPrint(g.arena, "@as(u64, types.{s})", .{zig_name}),
                    .c = try std.fmt.allocPrint(g.arena, "(unsigned long long)({s})", .{name}),
                });
            }
        }
    }

    // What is generated, in the registry's order.
    var bases: std.ArrayList(*const reg.TypeDef) = .empty;
    var handles: std.ArrayList(*const reg.TypeDef) = .empty;
    var enums: std.ArrayList(*const reg.TypeDef) = .empty;
    var flags: std.ArrayList(*const reg.TypeDef) = .empty;
    var pointers: std.ArrayList(*const reg.TypeDef) = .empty;
    var records: std.ArrayList(*const reg.TypeDef) = .empty;
    for (g.r.type_list) |def| {
        if (def.alias_of != null or !g.needed.contains(def.name)) continue;
        switch (def.category) {
            .basetype => try bases.append(g.arena, def),
            .handle => try handles.append(g.arena, def),
            .enumeration => try enums.append(g.arena, def),
            .bitmask => try flags.append(g.arena, def),
            .funcpointer => try pointers.append(g.arena, def),
            .structure, .union_ => try records.append(g.arena, def),
            .external => {},
        }
    }

    // ---- base types -----------------------------------------------------
    if (bases.items.len > 0) try banner(g, &out, "Scalars");
    for (bases.items) |def| {
        const inner = def.node.child("type").?;
        const inner_name = try inner.textContent(g.arena);
        const text = try def.node.textContent(g.arena);
        if (std.mem.indexOfScalar(u8, text, '*') != null)
            return fail(g.arena, "{s} is a pointer typedef, which this generator has no Zig type for", .{def.name});
        const zig_name = try g.zigTypeName(def.name);
        try claim(g, &claimed, zig_name, def.name);
        try doc(g, &out, "", def.name, null);
        try put(g, &out, "pub const {s} = {s};\n\n", .{ zig_name, (try g.baseType("", inner_name)).text });
    }

    // ---- handles --------------------------------------------------------
    if (handles.items.len > 0) try banner(g, &out, "Handles");
    for (handles.items) |def| {
        const zig_name = try g.zigTypeName(def.name);
        try claim(g, &claimed, zig_name, def.name);
        try doc(g, &out, "", def.name, null);
        if (try def.isDispatchable(g.arena)) {
            try put(g, &out, "pub const {s} = *opaque {{}};\n\n", .{zig_name});
        } else {
            // Non-dispatchable handles are 64 bits on every platform, including
            // the 32-bit ones where the C headers spell them as `uint64_t`. An
            // enum makes each one its own type, and `none` is `VK_NULL_HANDLE`.
            try put(g, &out, "pub const {s} = enum(u64) {{ none = 0, _ }};\n\n", .{zig_name});
        }
        g.summary.handles += 1;
    }

    // ---- enums ----------------------------------------------------------
    if (enums.items.len > 0) try banner(g, &out, "Enumerations");
    for (enums.items) |def| {
        if (g.bits_to_flags.contains(def.name)) continue; // written with its flags
        const info = try g.enumInfo(def.name);
        if (info.is_flags) {
            try writeFlags(g, &out, &claimed, rows, def.name, info, def.name);
        } else {
            try writeEnum(g, &out, &claimed, rows, def, info);
        }
    }

    // ---- flags ----------------------------------------------------------
    if (flags.items.len > 0) try banner(g, &out, "Flags");
    for (flags.items) |def| {
        const bits_name = def.node.attr("requires") orelse def.node.attr("bitvalues");
        if (bits_name) |bits| {
            const info = try g.enumInfo(bits);
            try writeFlags(g, &out, &claimed, rows, def.name, info, bits);
        } else {
            // Reserved for future use: the registry names no bits.
            const width: []const u8 = if (def.node.child("type")) |t| blk: {
                const text = try t.textContent(g.arena);
                break :blk if (std.mem.eql(u8, text, "VkFlags64")) "u64" else "u32";
            } else "u32";
            const zig_name = try g.zigTypeName(def.name);
            try claim(g, &claimed, zig_name, def.name);
            try doc(g, &out, "", def.name, "Reserved for future use, and required to be zero today.");
            try put(g, &out, "pub const {s} = {s};\n\n", .{ zig_name, width });
        }
    }

    // ---- function pointers ---------------------------------------------
    if (pointers.items.len > 0) try banner(g, &out, "Function pointers");
    for (pointers.items) |def| {
        const zig_name = try g.zigTypeName(def.name);
        try claim(g, &claimed, zig_name, def.name);
        try doc(g, &out, "", def.name, null);

        var params: std.ArrayList(gen.Param) = .empty;
        var siblings: std.ArrayList(reg.Decl) = .empty;
        var it = def.node.elements();
        while (it.next()) |child| {
            if (!std.mem.eql(u8, child.tag, "param")) continue;
            const decl = try g.parseDecl(child);
            const raw = try g.paramName(decl);
            try params.append(g.arena, .{ .decl = decl, .zig_name = try g.id(raw), .raw_name = raw });
            try siblings.append(g.arena, decl);
        }
        const ret = try g.parseDecl(def.node.child("proto").?);

        try put(g, &out, "pub const {s} = *const fn (", .{zig_name});
        if (params.items.len == 0) {
            try put(g, &out, ") callconv(call) {s};\n\n", .{try g.declType("", ret, &.{}, .ret)});
        } else {
            try put(g, &out, "\n", .{});
            for (params.items) |p| {
                try put(g, &out, "    {s}: {s},\n", .{ p.zig_name, try g.declType("", p.decl, siblings.items, .param) });
            }
            try put(g, &out, ") callconv(call) {s};\n\n", .{try g.declType("", ret, &.{}, .ret)});
        }
        g.summary.function_pointers += 1;
    }

    // ---- structs and unions --------------------------------------------
    if (records.items.len > 0) try banner(g, &out, "Structs");
    for (records.items) |def| try writeRecord(g, &out, &claimed, rows, def);

    // ---- aliases --------------------------------------------------------
    try writeAliases(g, &out, &claimed);

    return out.items;
}

fn writeEnum(g: *Generator, out: *Out, claimed: *Claimed, rows: *std.ArrayList(Row), def: *const reg.TypeDef, info: *const gen.EnumInfo) Error!void {
    const zig_name = try g.zigTypeName(def.name);
    try claim(g, claimed, zig_name, def.name);
    try doc(g, out, "", def.name, def.node.attr("comment"));

    // The members, in the order a reader expects: zero and up, then the
    // negatives from -1 down, which puts `VkResult`'s successes before its
    // errors.
    var primaries: std.ArrayList(gen.Entry) = .empty;
    for (info.entries) |e| if (e.primary) try primaries.append(g.arena, e);
    std.mem.sort(gen.Entry, primaries.items, {}, entryLess);

    try put(g, out, "pub const {s} = enum(i32) {{\n", .{zig_name});
    for (primaries.items) |e| {
        if (e.number < std.math.minInt(i32) or e.number > std.math.maxInt(i32))
            return fail(g.arena, "{s}: {s} = {d} does not fit an i32", .{ def.name, e.reg_name, e.number });
        try put(g, out, "    {s} = {d},\n", .{ try g.id(e.zig_name), e.number });
    }
    // Open: a driver or an extension may hand back a value this library has
    // never heard of, and a closed enum would make that undefined behaviour.
    try put(g, out, "    _,\n", .{});

    var wrote_decl = false;
    for (info.entries) |e| {
        if (e.primary) continue;
        if (!wrote_decl) try put(g, out, "\n", .{});
        wrote_decl = true;
        const target = info.entries[e.target.?];
        try put(g, out, "    /// {s}, another name for {s}\n", .{ e.reg_name, target.reg_name });
        try put(g, out, "    pub const {s}: @This() = .{s};\n", .{ try g.id(e.zig_name), try g.id(target.zig_name) });
    }

    if (std.mem.eql(u8, def.name, g.w.result)) try writeResult(g, out, zig_name, primaries.items);
    try writeMethods(g, out, def.name, zig_name, wrote_decl or std.mem.eql(u8, def.name, g.w.result));
    try put(g, out, "}};\n\n", .{});

    for (info.entries) |e| {
        try rows.append(g.arena, .{
            .label = e.reg_name,
            .zig = try std.fmt.allocPrint(g.arena, "e(types.{s}.{s})", .{ zig_name, try g.id(e.zig_name) }),
            .c = try std.fmt.allocPrint(g.arena, "(unsigned long long)(long long)({s})", .{e.reg_name}),
        });
    }
    g.summary.enums += 1;
    g.summary.enumerants += info.entries.len;
}

fn entryLess(_: void, a: gen.Entry, b: gen.Entry) bool {
    const a_neg = a.number < 0;
    const b_neg = b.number < 0;
    if (a_neg != b_neg) return b_neg;
    const a_abs = if (a_neg) -a.number else a.number;
    const b_abs = if (b_neg) -b.number else b.number;
    return a_abs < b_abs;
}

/// `VkResult` is the one enum with a job beyond naming numbers: negative is a
/// failure, and a failure is a Zig error. The registry says which values those
/// are, so the error set is the negative ones - `VK_ERROR_OUT_OF_HOST_MEMORY`
/// is `error.OutOfHostMemory` - and `check` is the switch over them.
fn writeResult(g: *Generator, out: *Out, zig_name: []const u8, primaries: []const gen.Entry) Error!void {
    var errors: std.ArrayList([]const u8) = .empty;
    var arms: std.ArrayList(u8) = .empty;
    var seen: gen.Set = .empty;
    var has_unknown = false;

    for (primaries) |e| {
        if (e.number >= 0) continue;
        // `VK_ERROR_SURFACE_LOST_KHR` -> `SurfaceLost`; the tag is a vendor,
        // and a program does not care which vendor's extension lost the surface.
        var rest = e.reg_name;
        if (std.mem.startsWith(u8, rest, "VK_ERROR_")) rest = rest["VK_ERROR_".len..] else if (std.mem.startsWith(u8, rest, "VK_")) rest = rest[3..];
        if (names.trailingUpperTag(rest, g.r.tags)) |tag| rest = rest[0 .. rest.len - tag.len - 1];
        const error_name = try names.pascal(g.arena, rest);
        if (std.mem.eql(u8, error_name, "Unknown")) has_unknown = true;
        if (seen.contains(error_name)) continue;
        try seen.put(g.arena, error_name, {});
        try errors.append(g.arena, error_name);
        try arms.print(g.arena, "            .{s} => error.{s},\n", .{ try g.id(e.zig_name), error_name });
    }
    if (!has_unknown) try errors.append(g.arena, "Unknown");

    try put(g, out,
        \\
        \\    /// Every failure a Vulkan command can report, as a Zig error.
        \\    pub const Error = error{{
        \\
    , .{});
    for (errors.items) |e| try put(g, out, "        {s},\n", .{e});
    try put(g, out,
        \\    }};
        \\
        \\    /// Did the command succeed?
        \\    pub fn succeeded(self: {s}) bool {{
        \\        return @intFromEnum(self) >= 0;
        \\    }}
        \\
        \\    /// Turn a failure into an error, and hand a success straight back.
        \\    ///
        \\    /// The result comes back rather than being swallowed, because the
        \\    /// successes are not interchangeable: `incomplete` and `suboptimal_khr`
        \\    /// are both success, and both mean you have something else to do. A
        \\    /// negative code this library has no name for is `error.Unknown`.
        \\    pub fn check(self: {s}) Error!{s} {{
        \\        return switch (self) {{
        \\{s}            else => if (self.succeeded()) self else error.Unknown,
        \\        }};
        \\    }}
        \\
    , .{ zig_name, zig_name, zig_name, arms.items });
}

/// The declarations a type gets from the hand-written `methods.zig`.
fn writeMethods(g: *Generator, out: *Out, reg_name: []const u8, zig_name: []const u8, has_body: bool) Error!void {
    var first = true;
    for (g.w.methods) |m| {
        if (!std.mem.eql(u8, m.type, reg_name)) continue;
        for (m.decls) |d| {
            if (first and has_body) try put(g, out, "\n", .{});
            if (first and !has_body) try put(g, out, "\n", .{});
            first = false;
            try put(g, out, "    pub const {s} = methods.{s}.{s};\n", .{ d, zig_name, d });
        }
    }
}

fn writeFlags(
    g: *Generator,
    out: *Out,
    claimed: *Claimed,
    rows: *std.ArrayList(Row),
    flags_reg_name: []const u8,
    info: *const gen.EnumInfo,
    bits_reg_name: []const u8,
) Error!void {
    const zig_name = try g.zigTypeName(flags_reg_name);
    try claim(g, claimed, zig_name, flags_reg_name);
    const width: u8 = info.bits;
    if (width != 32 and width != 64) return fail(g.arena, "{s}: a flags type of {d} bits", .{ flags_reg_name, width });

    try doc(g, out, "", flags_reg_name, null);
    try put(g, out, "pub const {s} = packed struct(u{d}) {{\n", .{ zig_name, width });

    var primaries: std.ArrayList(gen.Entry) = .empty;
    for (info.entries) |e| if (e.primary) try primaries.append(g.arena, e);
    std.mem.sort(gen.Entry, primaries.items, {}, bitLess);

    var next_bit: u16 = 0;
    for (primaries.items) |e| {
        if (e.bit >= width)
            return fail(g.arena, "{s}: {s} is bit {d}, which does not fit {d} bits", .{ flags_reg_name, e.reg_name, e.bit, width });
        if (e.bit > next_bit) {
            try put(g, out, "    _reserved_{d}: u{d} = 0,\n", .{ next_bit, e.bit - next_bit });
        }
        try put(g, out, "    {s}: bool = false,\n", .{try g.id(e.zig_name)});
        next_bit = @as(u16, e.bit) + 1;
    }
    if (next_bit < width) try put(g, out, "    _reserved: u{d} = 0,\n", .{width - next_bit});

    try put(g, out,
        \\
        \\    /// Does this set have every bit of `wanted` set?
        \\    pub fn contains(self: {s}, wanted: {s}) bool {{
        \\        const have: u{d} = @bitCast(self);
        \\        const need: u{d} = @bitCast(wanted);
        \\        return have & need == need;
        \\    }}
        \\
    , .{ zig_name, zig_name, width, width });

    // What is not one bit - zero, and combinations like `ALL_GRAPHICS` - and
    // the other names for the bits that are.
    for (info.entries) |e| {
        if (e.primary) continue;
        try put(g, out, "\n    /// {s}\n    pub const {s}: {s} = @bitCast(@as(u{d}, {d}));\n", .{ e.reg_name, try g.id(e.zig_name), zig_name, width, e.number });
    }
    try writeMethods(g, out, flags_reg_name, zig_name, true);
    try put(g, out, "}};\n\n", .{});
    g.summary.flags += 1;

    // A FlagBits name that something used as a type is another name for this.
    if (!std.mem.eql(u8, bits_reg_name, flags_reg_name) and g.bits_referenced.contains(bits_reg_name)) {
        const alias = try g.zigTypeName(bits_reg_name);
        try claim(g, claimed, alias, bits_reg_name);
        try doc(g, out, "", bits_reg_name, null);
        try put(g, out, "pub const {s} = {s};\n\n", .{ alias, zig_name });
        g.summary.aliases += 1;
    }

    for (info.entries) |e| {
        const zig = if (e.primary)
            try std.fmt.allocPrint(g.arena, "f(types.{s}{{ .{s} = true }})", .{ zig_name, try g.id(e.zig_name) })
        else
            try std.fmt.allocPrint(g.arena, "f(types.{s}.{s})", .{ zig_name, try g.id(e.zig_name) });
        try rows.append(g.arena, .{
            .label = e.reg_name,
            .zig = zig,
            .c = try std.fmt.allocPrint(g.arena, "(unsigned long long)({s})", .{e.reg_name}),
        });
    }
    g.summary.enumerants += info.entries.len;
}

fn bitLess(_: void, a: gen.Entry, b: gen.Entry) bool {
    return a.bit < b.bit;
}

fn writeRecord(g: *Generator, out: *Out, claimed: *Claimed, rows: *std.ArrayList(Row), def: *const reg.TypeDef) Error!void {
    const zig_name = try g.zigTypeName(def.name);
    try claim(g, claimed, zig_name, def.name);
    const is_union = def.category == .union_;

    const members = try g.members(def);
    var siblings: std.ArrayList(reg.Decl) = .empty;
    for (members) |m| try siblings.append(g.arena, m.decl);

    // A struct of nothing but switches - features - starts with all of them
    // off; so does anything `zero_defaults` names.
    var all_bool = members.len > 0;
    var real_members: usize = 0;
    for (members) |m| {
        if (std.mem.eql(u8, m.decl.name, "sType") or std.mem.eql(u8, m.decl.name, "pNext")) continue;
        real_members += 1;
        if (!std.mem.eql(u8, g.r.canonical(m.decl.type_name), "VkBool32") or m.decl.pointerDepth() != 0 or m.decl.dims.len != 0) all_bool = false;
    }
    const all_zero = (all_bool and real_members > 0) or gen.contains(g.w.zero_defaults, def.name);

    try doc(g, out, "", def.name, def.node.attr("comment"));
    try put(g, out, "pub const {s} = extern {s} {{\n", .{ zig_name, if (is_union) "union" else "struct" });

    var used: gen.Set = .empty;
    for (members) |m| {
        if (used.contains(m.raw_name))
            return fail(g.arena, "{s} has two members called '{s}' in Zig", .{ def.name, m.raw_name });
        try used.put(g.arena, m.raw_name, {});

        if (m.decl.comment) |c| try docLine(g, out, "    ", c);
        const text = try g.declType("", m.decl, siblings.items, .member);
        if (try g.memberDefault(def, m, siblings.items, all_zero, text)) |d| {
            try put(g, out, "    {s}: {s} = {s},\n", .{ m.zig_name, text, d });
        } else {
            try put(g, out, "    {s}: {s},\n", .{ m.zig_name, text });
        }
    }
    try writeMethods(g, out, def.name, zig_name, members.len > 0);
    try put(g, out, "}};\n\n", .{});

    if (is_union) g.summary.unions += 1 else g.summary.structs += 1;

    // The oracle's rows: size, alignment, and every member's offset.
    try rows.append(g.arena, .{
        .label = try std.fmt.allocPrint(g.arena, "sizeof({s})", .{def.name}),
        .zig = try std.fmt.allocPrint(g.arena, "@sizeOf(types.{s})", .{zig_name}),
        .c = try std.fmt.allocPrint(g.arena, "(unsigned long long)sizeof({s})", .{def.name}),
    });
    try rows.append(g.arena, .{
        .label = try std.fmt.allocPrint(g.arena, "alignof({s})", .{def.name}),
        .zig = try std.fmt.allocPrint(g.arena, "@alignOf(types.{s})", .{zig_name}),
        .c = try std.fmt.allocPrint(g.arena, "(unsigned long long)_Alignof({s})", .{def.name}),
    });
    for (members) |m| {
        try rows.append(g.arena, .{
            .label = try std.fmt.allocPrint(g.arena, "offsetof({s}, {s})", .{ def.name, m.decl.name }),
            .zig = if (is_union) "0" else try std.fmt.allocPrint(g.arena, "@offsetOf(types.{s}, \"{s}\")", .{ zig_name, m.raw_name }),
            .c = try std.fmt.allocPrint(g.arena, "(unsigned long long)offsetof({s}, {s})", .{ def.name, m.decl.name }),
        });
    }
}

/// Types the registry gives a second name - a promoted extension's - and that
/// a selected feature or extension asks for by that name.
fn writeAliases(g: *Generator, out: *Out, claimed: *Claimed) Error!void {
    const wanted_names = try requiredTypeNames(g);
    var wrote_banner = false;
    for (g.r.type_list) |def| {
        const target = def.alias_of orelse continue;
        if (!wanted_names.contains(def.name)) continue;
        const canon = g.r.canonical(target);
        if (!g.needed.contains(canon)) {
            // A FlagBits name is spelled as its flags type, which may be needed.
            const flags = g.bits_to_flags.get(canon) orelse continue;
            if (!g.needed.contains(flags)) continue;
        }
        const zig_name = try g.zigTypeName(def.name);
        if (claimed.contains(zig_name)) continue; // already written, as a FlagBits alias
        const base = try g.baseType("", canon);

        if (!wrote_banner) try banner(g, out, "Aliases: the names extensions had before they were promoted");
        wrote_banner = true;
        try claim(g, claimed, zig_name, def.name);
        try doc(g, out, "", def.name, null);
        try put(g, out, "pub const {s} = {s};\n\n", .{ zig_name, base.text });
        g.summary.aliases += 1;
    }
}

// -------------------------------------------------------------------------
// commands.zig
// -------------------------------------------------------------------------

pub fn commands(g: *Generator) Error![]const u8 {
    var out: Out = .empty;
    try header(g, &out, "The command tables: what to load from a Vulkan implementation, by scope.");
    try put(g, &out,
        \\//!
        \\//! Ordinary structs of the kind `dispatch.load` fills in, one per scope. A field is
        \\//! the command's name without `vk`, with its first letter lower-case: `cmdDraw` is
        \\//! `vkCmdDraw`. A plain function pointer is a command every Vulkan 1.0 device has;
        \\//! an optional one is from a later version or an extension, and is `null` on a
        \\//! device that has neither. A promoted command's older name is in `aliases`.
        \\
        \\const types = @import("types.zig");
        \\const call = @import("../types.zig").call;
        \\
    , .{});

    const tiers = [_]gen.Tier{ .global, .instance, .device };
    const blurb = [_][]const u8{
        "What exists before there is an instance, resolved against a null one.",
        "What dispatches on an instance or a physical device, through the loader's trampoline.",
        "What dispatches on a device, a queue or a command buffer, straight into the driver.",
    };
    const table_name = [_][]const u8{ "Global", "Instance", "Device" };

    for (tiers, 0..) |tier, tier_index| {
        var list: std.ArrayList(gen.WantedCommand) = .empty;
        for (g.commands.items) |c| if (c.tier == tier) try list.append(g.arena, c);
        std.mem.sort(gen.WantedCommand, list.items, {}, commandLess);

        try put(g, &out, "\n/// {s}\npub const {s} = struct {{\n", .{ blurb[tier_index], table_name[tier_index] });

        var any_alias = false;
        for (list.items, 0..) |c, index| {
            if (index > 0) try put(g, &out, "\n", .{});
            try put(g, &out, "    /// {s}\n", .{c.name});
            if (!c.required) try put(g, &out, "    ///\n    /// Optional: from {s}.\n", .{c.provenance});

            const optional = if (c.required) "" else "?";
            try put(g, &out, "    {s}: {s}*const fn (\n", .{ try g.id(c.field), optional });

            var siblings: std.ArrayList(reg.Decl) = .empty;
            for (c.params) |p| try siblings.append(g.arena, p.decl);
            for (c.params) |p| {
                try put(g, &out, "        {s}: {s},\n", .{ p.zig_name, try g.declType("types.", p.decl, siblings.items, .param) });
            }
            try put(g, &out, "    ) callconv(call) {s},\n", .{try g.declType("types.", c.ret, &.{}, .ret)});

            if (c.aliases.len > 0) any_alias = true;
            switch (tier) {
                .global => g.summary.global += 1,
                .instance => g.summary.instance += 1,
                .device => g.summary.device += 1,
            }
            if (!c.required) g.summary.optional += 1;
        }

        if (any_alias) {
            try put(g, &out, "\n    /// Promoted commands answer to the name they had as an extension, on a\n    /// driver old enough to have only that.\n    pub const aliases = .{{\n", .{});
            for (list.items) |c| {
                if (c.aliases.len == 0) continue;
                try put(g, &out, "        .{s} = .{{", .{try g.id(c.field)});
                for (c.aliases, 0..) |a, i| try put(g, &out, "{s}\"{s}\"", .{ if (i > 0) ", " else "", a });
                try put(g, &out, "}},\n", .{});
            }
            try put(g, &out, "    }};\n", .{});
        }
        try put(g, &out, "}};\n", .{});
    }
    return out.items;
}

fn commandLess(_: void, a: gen.WantedCommand, b: gen.WantedCommand) bool {
    return a.order < b.order;
}

// -------------------------------------------------------------------------
// layout.zig and layout.c
// -------------------------------------------------------------------------

pub fn layoutZig(g: *Generator, rows: []const Row) Error![]const u8 {
    var out: Out = .empty;
    try header(g, &out, "What Zig makes of every struct and every enumerant, to be compared with what C makes of them.");
    try put(g, &out,
        \\//!
        \\//! `values[i]` is the number Zig gets for `labels[i]`; `layout.c` computes the same
        \\//! list from the real Vulkan headers, in the same order. Every entry is a size, an
        \\//! alignment, a member offset, an enumerant or a constant. The test that compares
        \\//! the two is in `oracle.zig`.
        \\
        \\const types = @import("types.zig");
        \\
        \\/// An enum's number, as the bits C would print for it.
        \\fn e(value: anytype) u64 {{
        \\    return @bitCast(@as(i64, @intFromEnum(value)));
        \\}}
        \\
        \\/// A flags value's bits.
        \\fn f(value: anytype) u64 {{
        \\    const Int = @Int(.unsigned, @bitSizeOf(@TypeOf(value)));
        \\    return @as(Int, @bitCast(value));
        \\}}
        \\
        \\pub const values = blk: {{
        \\    @setEvalBranchQuota(10_000_000);
        \\    break :blk [_]u64{{
        \\
    , .{});
    for (rows) |row| try put(g, &out, "        {s},\n", .{row.zig});
    try put(g, &out, "    }};\n}};\n\npub const labels = [_][]const u8{{\n", .{});
    for (rows) |row| try put(g, &out, "    \"{s}\",\n", .{row.label});
    try put(g, &out, "}};\n", .{});
    return out.items;
}

pub fn layoutC(g: *Generator, rows: []const Row) Error![]const u8 {
    var out: Out = .empty;
    try put(g, &out,
        \\/* SPDX-License-Identifier: BSL-1.0 */
        \\
        \\/*
        \\ * GENERATED by tools/genvk.zig from the Vulkan registry. Do not edit: change
        \\ * tools/wanted.zon and run `zig build gen -Dvk-xml=<path to vk.xml>`.
        \\ *
        \\ * What the real Vulkan headers make of every struct and enumerant that
        \\ * types.zig declares: sizes, alignments, member offsets, values. `layout.zig`
        \\ * lists the same things in the same order with the numbers Zig gets.
        \\ *
        \\ *     zig cc -I<Vulkan SDK>/Include -DFLUXION_MAIN layout.c
        \\ *
        \\ * prints one number per line. Compiled with -S for another target, the table
        \\ * is in the assembly and nothing has to run.
        \\ */
        \\
        \\#include <stddef.h>
        \\#include <stdint.h>
        \\
    , .{});

    // The native types the platform headers name and do not define.
    try put(g, &out, "\n/* The platforms' own types, as much as Vulkan's headers need of them. */\n", .{});
    for (g.w.platform_types) |p| try put(g, &out, "{s}\n", .{p.c});

    try put(g, &out, "\n#include <vulkan/vulkan_core.h>\n", .{});

    // The platform headers whose structs are in the list.
    var platforms: std.ArrayList([]const u8) = .empty;
    for (g.r.providers) |p| {
        if (!g.isSelected(p.name)) continue;
        const platform = p.platform orelse continue;
        var used = false;
        for (p.requires) |req| for (req.types) |t| {
            if (g.needed.contains(g.r.canonical(t))) used = true;
        };
        if (!used) continue;
        var seen = false;
        for (platforms.items) |x| if (std.mem.eql(u8, x, platform)) {
            seen = true;
        };
        if (!seen) try platforms.append(g.arena, platform);
    }
    std.mem.sort([]const u8, platforms.items, {}, lessThanString);
    for (platforms.items) |p| try put(g, &out, "#include <vulkan/vulkan_{s}.h>\n", .{p});

    try put(g, &out,
        \\
        \\const unsigned long long fluxion_layout[] = {{
        \\
    , .{});
    for (rows) |row| try put(g, &out, "    {s}, /* {s} */\n", .{ row.c, row.label });
    try put(g, &out,
        \\}};
        \\
        \\#ifdef FLUXION_MAIN
        \\#include <stdio.h>
        \\int main(void) {{
        \\    for (size_t i = 0; i < sizeof(fluxion_layout) / sizeof(fluxion_layout[0]); i++)
        \\        printf("%llu\n", fluxion_layout[i]);
        \\    return 0;
        \\}}
        \\#endif
        \\
    , .{});
    return out.items;
}
